sudo: required
language: java
jdk:
        - oraclejdk8
services:
        - docker

before_install:
        - echo "Testing Docker Hub Credentials"
        - docker login u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - echo "Docker Hub credentials are working"

script: 
        - mvn package
        - mvn docker:build
after_sucess:
        - docker push opas350/final-accenture-project
