sudo: required
language: java
jdk:
        - oraclejdk8
services:
        - docker
cache:
        directories:
                - $HOME/.m2
script:
        - echo "Testing Docker Hub Credentials"
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - echo "Docker Hub credentials are working"
        - mvn package
        - mvn docker:build
        - docker push opas350/final-accenture-project
