sudo: required
language: java
jdk:
        - oraclejdk8
services:
        - docker

script: 
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - mvn package
        - mvn docker:build
        - docker push opas350/final-accenture-project
